/*
 * Stub for class facerecog.FrameProcess
 * Generated by Sapphire Compiler (sc).
 */
package facerecog.stubs;


public final class FrameProcess_Stub extends facerecog.FrameProcess implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public FrameProcess_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of processFrame(String)
    public void processFrame(java.lang.String $param_String_1)
            throws java.io.IOException, java.lang.InterruptedException {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.processFrame( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void facerecog.FrameProcess.processFrame(java.lang.String) throws java.io.IOException,java.lang.InterruptedException";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
